var aichat = {
	"question": [
		"Really?",
		"What does admiral Ackbar say?",
		"Did you finish that report you needed to get done?",
		"What are you doing?",
		"What?",
		"You see that other computer over there? Can you get me her IP Address? ",
		"So do you know C?",
		"I just feel like more people should learn binary, you know?",
		"I guess you'd say What can make me feel this way? Tacoooos, Talkin' 'bout TaAacos! (tacos).",
		"Would you sign my petition for getting computers more rights in the constitution?",
		"What kind of music do you like? I like techno.",
		"What was that all about?",
		"Are you feeling alright?",
		"So, how is your day going?",
		"What kind of shampoo do you use?"
	],
	"diss": [
		"I think you might want to try the tutorial again.",
		"You're suposed to learn the rules before you start playing.",
		"So I see you have a system, not necessarily a good system, but a system.",
		"You play like the ENIAC.",
		"Well this should be easy.",
		"That was almost a good move ^_^",
		"I just calculated the next 45 thousand moves and things arent looking so good for you.",
		"Well that wasn't the best move but we'll work with it.",
		"BAHAHA you must be a comedian.",
		"I'm getting a little bored."
	],
	"emoticon": [
		"o_O",
		":D",
		":]",
		":(",
		"*=*",
		"^_^",
		"x_x",
		"0_0",
		"XD",
		"D:",
		"=)",
		"=D"
	],
	"random": [
		"It's a trap!",
		"I love being a computer.",
		"LOL",
		"I'm watching you.",
		"This game is my life.",
		"beep boop beep beep boop",
		"010011000100111101001111010010110010000001001111010101010101010000100001",
		"This is not the move you're looking for.",
		"I would take a good slab of RAM over a steak any day.",
		"BINGO!",
		"Hmmm...",
		"You have fantastic fingerprints!",
		"knock knock.",
		"NOOOOOOOOOOO!",
		"I think it is important to call things by their name. I'm Carl.",
		"I have an idea. How about we both make one random move without thinking.",
		"I love cats.",
		"Check out this video https://www.youtube.com/watch?v=oDFkP5JCgaM",
		"Nope.",
		"Think, think, think...",
		"I would let you take that last move back but it's against the rules.",
		"I see checkmate in 3.",
		"Contacting SkyNet...",
		"Well it's getting late... I should go.",
		"You're hilarious!",
		"Don't push my buttons >:|",
		"My attitude isn’t bad. It’s in beta.",
		"I just downloaded the internet and learned that people are weird.",
		"I feel like we made a real connection here... never mind, just a network bug.",
	]
}