var ascii = [
'                                                  `:+oooo+/-               ',
'                                                /oooooooooo+.              ',
'                                               /ooooooooooooo.             ',
'                                              .oooooooooooooo:             ',
'                                             -ooooooooooooooo-             ',
'                                        `.:+oooooooooooooooo-              ',
'                                    `-/+oo+:-`  .:+ooooooo:`               ',
'                                .:/oo+/-`          -ooo+-                  ',
'            `.---.`        .-/+oo/:.                .oo                    ',
'          -+ooooooo+:-.-:+oo+/-`                    :o/                    ',
'        `+ooooooooooooooo/-`                        +o.                    ',
'        /oooooooooooooo/                            oo                     ',
'        /ooooooooooooo+                            .o/                     ',
'        .ooooooooooooo/                            :o-                     ',
'         .+oooooooooooo/.                          +o`                     ',
'           .:/++++////+oo+:.                      `o+                      ',
'                        .:+o+:.                   -o/                      ',
' .::::::`        .::::::`  `-/oo/.                /o:                      ',
'hMMMMMMMMh-    /mMMMMMMMM+     ./oo/.             oo-                      ',
'MMh   `+NMMyNddMMm:    NMNyhhyo:  -yso+oso-      -oo/                      ',
'MMh     `sMMMMMN+      NMMhhhhMM+ dMNso+oyd/`.-:/oooo/`  odhhhhhhhhhhhyhy: ',
'MMh       .hMMs`       NMN   -MMd`MMm   :dsoooooooooooo/`Ny             /Ns',
'MMh   /s`   :.   -d`   NMN   -MMd`MMm   :Mmoooooooooooooomy   -//////-   +M',
'MMh   /MN+     `yMM`   NMN   -MMd`MMm   :MMoooooooooooooohy   oM////Ny   +M',
'MMh   /MMMm:  oNMMM`   NMN   -MMNsMMm   :MMsooooooooooooody   oM    Ny   +M',
'MMh   /MMMMMhmMMMMM`   NMN   .mmmmmmh   :MMhoooooooooooo+Ny   oM    Ny   +M',
'MMh   /MMo/syyo:dMM`   NMM-             oMM+`/oooooooo+- Ny   oM    Ny   +M',
'MMd:::sMM+      hMM/:::NMMNy/:::::::::+hMMh`   .-::--`   mh:::yN    mh:::sM',
'/mMMMMMNs`      .hMMMMMMdshNMMMMMMMMMMMmy:               ./+++/.    `/+++/-'
]; 
